### PR TITLE
add uscis simulated homepage

### PR DESCRIPTION
**Pull request by brendansudol**
__Why__
To help agencies visualize what experience will look/feel like upon login.gov integration

### CODE REVIEW

**Comment by brendansudol** [comment]
this look ok to you, @sashax?

**Comment by sashax** [comment]
I'll get to it this morning. In the midst of some SAML debugging

**Comment by brendansudol** [comment]
cool, no rush!

**Comment by sashax** [comment]
LGTM, although I think we also want a way to invoke the login from the agency page, right?

**Comment by brendansudol** [comment]
cool, thanks, yeah i was going to roll out the login button hook in another PR

**Comment by sashax** [comment]
ok, then LGTM!

**Comment by brendansudol** [comment]
🎉

**Pull request merged**
